ARG UBUNTU_VERSION=18.04
ARG COMPILER=gcc
FROM svalinn/dagmc-ci-ubuntu-${UBUNTU_VERSION}-${COMPILER}-ext AS base

# HDF5 argument possible value: 1.10.4 or system
ARG HDF5=1.10.4
ENV HDF5_VERSION=${HDF5}

if [ "${HDF5_VERSION:3:1}" == "." ]; then
  HDF5_VERSION_major=${HDF5_VERSION::3}
elif [ "${HDF5_VERSION:4:1}" == "." ]; then
  HDF5_VERSION_major=${HDF5_VERSION::4}
fi

# Set HDF5 env variable
ENV hdf5_build_dir=${build_dir}/hdf5
ENV hdf5_install_dir=${install_dir}/hdf5

RUN rm -rf ${hdf5_build_dir}/bld ${hdf5_install_dir}; \
    mkdir -p ${hdf5_build_dir}/bld; \
    cd ${hdf5_build_dir}; \
    wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-${HDF5_VERSION_major}/hdf5-${HDF5_VERSION}/src/hdf5-${HDF5_VERSION}.tar.gz; \
    tar_chashum=$(sha256sum hdf5-${HDF5_VERSION}.tar.gz | cut -d' ' -f1); \
    if [ $hdf5_1_10_4_shasum != $tar_chashum ]; then \
        echo "Bad shasum for hdf5 tar!"; \
        exit 1; \
    fi

RUn tar -xzf hdf5-${HDF5_VERSION}.tar.gz; \
    cd bld; \
    ../hdf5-${HDF5_VERSION}/configure --enable-shared \
                     --prefix=${hdf5_install_dir} \
                     CC=${CC} CXX=${CXX}; \
    make -j${ci_jobs}; \
    make install; \
    cd; \
    rm -rf ${hdf5_build_dir}