ARG UBUNTU_VERSION=18.04
ARG COMPILER=gcc
ARG HDF5=1.10.4
FROM svalinn/dagmc-ci-ubuntu-${UBUNTU_VERSION}-${COMPILER}-ext-hdf5_${HDF5} AS base

# MOAB Verions: 5.1.0
ARG MOAB=5.1.0
ENV MOAB_VERSION ${MOAB}

FROM base AS branch-${MOAB_VERSION}
ENV moab_branch=Version${MOAB_VERSION}

FROM base AS branch-master
ENV moab_branch=${MOAB_VERSION}

FROM base AS branch-develop
ENV moab_branch=${MOAB_VERSION}

FROM branch-${MOAB_VERSION} 

# Set MOAB env variable
ENV moab_build_dir=${build_dir}/moab
ENV moab_install_dir=${install_dir}/moab

RUN rm -rf ${moab_build_dir}/bld ${moab_install_dir}; \
    mkdir -p ${moab_build_dir}/bld; \
    cd ${moab_build_dir}; \
    git clone --depth 1 https://bitbucket.org/fathomteam/moab -b ${moab_branch}
    
RUN cd ${moab_build_dr}/bld; \
    cmake ../moab -DENABLE_HDF5=ON -DHDF5_ROOT=${hdf5_install_dir} \
                  -DENABLE_BLASLAPACK=OFF \
                  -DENABLE_FORTRAN=OFF \
                  -DCMAKE_INSTALL_PREFIX=${moab_install_dir} \
                  -DCMAKE_C_COMPILER=${CC} \
                  -DCMAKE_CXX_COMPILER=${CXX} \
                  -DBUILD_SHARED_LIBS=OFF; \
    make -j${ci_jobs}; \
    make install; \
    rm -rf *

RUN cd ${moab_build_dr}/bld; \
    cmake ../moab -DENABLE_HDF5=ON -DHDF5_ROOT=${hdf5_install_dir} \
                  -DENABLE_PYMOAB=ON \
                  -DENABLE_BLASLAPACK=OFF \
                  -DENABLE_FORTRAN=OFF \
                  -DCMAKE_INSTALL_PREFIX=${moab_install_dir} \
                  -DCMAKE_C_COMPILER=${CC} \
                  -DCMAKE_CXX_COMPILER=${CXX} \
                  -DBUILD_SHARED_LIBS=ON \
                  -DCMAKE_INSTALL_RPATH=${hdf5_install_dir}/lib:${moab_install_dir}/lib; \
    make -j${ci_jobs}; \
    make install; \
    cd; \
    rm -rf ${moab_build_dir}
