ARG UBUNTU_VERSION=18.04
FROM svalinn/dagmc-ci-ubuntu-${UBUNTU_VERSION} AS base

#setting the COMPILER variable
ARG COMPILER=gcc
ENV COMPILER=${COMPILER}

# explicitly set compiler variables
ENV  FC=`which gfortran`

FROM base AS branch-version-gcc
ENV CC=`which gcc`
ENV CXX=`which g++`
ENV ci_jobs="4"

FROM base AS branch-version-clang
ENV  CC=`which clang`
ENV CXX=`which clang++`

FROM branch-version-${COMPILER}

# Set Geant4 env variable
ENV geant4_build_dir=${build_dir}/geant4
ENV geant4_install_dir=${install_dir}/geant4

# Build Geant4
ENV geant4_version=10.5.1
ENV geant4_basename=geant4-v${geant4_version}
ENV geant4_tarball=${geant4_basename}.tar.gz
ENV geant4_shasum=2397eb859dc4de095ff66059d8bda9f060fdc42e10469dd7890946293eeb0e39

RUN rm -rf ${geant4_build_dir}/bld ${geant4_install_dir}; \
    mkdir -p ${geant4_build_dir}/bld; \
    cd ${geant4_build_dir}; \
    wget https://gitlab.cern.ch/geant4/geant4/-/archive/v${geant4_version}/${geant4_tarball} --no-check-certificate; \
    tar_chashum=$(sha256sum ${geant4_tarball} | cut -d' ' -f1); \
    if [ $geant4_shasum != $tar_chashum ]; then \
       echo "Bad shasum for Geant4 tar!"; \
       exit 1; \
    fi

RUN cd ${geant4_build_dir}; \
    tar -xzf ${geant4_tarball}; \
    cd bld; \
    cmake ../${geant4_basename} -DBUILD_STATIC_LIBS=ON \
                 -DGEANT4_USE_SYSTEM_EXPAT=OFF \
                 -DCMAKE_BUILD_TYPE=Release \
                 -DCMAKE_C_COMPILER=${CC} \
                 -DCMAKE_CXX_COMPILER=${CXX} \
                 -DCMAKE_INSTALL_RPATH=${geant4_install_dir}/lib \
                 -DCMAKE_INSTALL_PREFIX=${geant4_install_dir}; \
    make -j${ci_jobs}; \
    make install; \
    cd; \
    rm -rf ${geant4_build_dir}    

ENV double_down_build_dir=${build_dir}/double-down/
ENV double_down_install_dir=${install_dir}/double-down/

# Build Embree
RUN /root/etc/CI/docker/build_embree.sh

# Embree Variables
ENV EMBREE_TAG='v3.6.1'
ENV EMBREE_REPO='https://github.com/embree/embree'

# Set Geant4 env variable
ENV embree_build_dir=${build_dir}/embree
ENV embree_install_dir=${install_dir}/embree

# Embree Install
RUN rm -rf ${embree_build_dir}/bld ${embree_install_dir}; \
    mkdir -p ${embree_build_dir}/bld; \
    cd ${embree_build_dir}; \
    git clone -b $EMBREE_TAG $EMBREE_REPO; \
    cd bld
    cmake ../embree -DCMAKE_INSTALL_PREFIX=${embree_install_dir} \
        -DEMBREE_ISPC_SUPPORT=OFF \
        -DEMBREE_TASKING_SYSTEM=INTERNAL \
        -DEMBREE_TUTORIALS=OFF \
        -DEMBREE_TBB_ROOT=/usr
    make -j${ci_jobs}2; \
    make -j${ci_jobs} install; \
    cd; \
    rm -rf ${embree_build_dir}
